#!/usr/bin/php
<?php
$consumerKey = getenv('consumerKey');
$consumerSecret = getenv('consumerSecret');
$token = getenv('token');
$tokenSecret = getenv('tokenSecret');

$arguments = getopt('F:X:h:e:pv', array('encode::'));
$host = 'localhost';
if(isset($arguments['h']))
  $host = $arguments['h'];
$method = 'get';
if(isset($arguments['X']))
  $method = strtolower($arguments['X']);
$endpoint = '/photos/pageSize-3/list.json';
if(isset($arguments['e']))
  $endpoint = $arguments['e'];
$pretty = false;
if(isset($arguments['p']))
  $pretty = true;
$verbose = false;
if(isset($arguments['v']))
  $verbose = true;
$encode = false;
if(isset($arguments['encode']))
  $encode = true;

$fields = array();
if(isset($arguments['F']))
{
  foreach((array)$arguments['F'] as $field)
  {
    $parts = explode('=', $field);
    if($encode && $parts[0] == 'photo' && strncmp($parts[1][0], '@', 1) == 0 && is_file(substr($parts[1], 1)))
      $fields[$parts[0]] = base64_encode(file_get_contents(substr($parts[1], 1)));
    else
      $fields[$parts[0]] = $parts[1];
  }
}

include 'OpenPhotoOAuth.php';
$client = new OpenPhotoOAuth($host, $consumerKey, $consumerSecret, $token, $tokenSecret);
if($method == 'get')
  $resp = $client->get($endpoint, $fields);
elseif($method == 'post')
  $resp = $client->post($endpoint, $fields);

if($verbose)
  echo sprintf("==========\nMethod: %s\nHost: %s\nEndpoint: %s\n==========\n\n", $method, $host, $endpoint);

if($pretty)
  echo indent($resp);
else
  echo $resp;

if($verbose || $pretty)
  echo "\n";

// from https://gist.github.com/906036
function indent($json) {

  $result      = '';
  $pos         = 0;
  $strLen      = strlen($json);
  $indentStr   = '  ';
  $newLine     = "\n";
  $prevChar    = '';
  $outOfQuotes = true;

  for ($i=0; $i<=$strLen; $i++) {

    // Grab the next character in the string.
    $char = substr($json, $i, 1);

    // Put spaces in front of :
    if ($outOfQuotes && $char == ':' && $prevChar != ' ') {
      $result .= ' ';
    }
    
    if ($outOfQuotes && $char != ' ' && $prevChar == ':') {
      $result .= ' ';
    }

    // Are we inside a quoted string?
    if ($char == '"' && $prevChar != '\\') {
      $outOfQuotes = !$outOfQuotes;

      // If this character is the end of an element, 
      // output a new line and indent the next line.
    } else if(($char == '}' || $char == ']') && $outOfQuotes) {
      $result .= $newLine;
      $pos --;
      for ($j=0; $j<$pos; $j++) {
        $result .= $indentStr;
      }
    }

    // Add the character to the result string.
    $result .= $char;
    
    // If the last character was the beginning of an element, 
    // output a new line and indent the next line.
    if (($char == ',' || $char == '{' || $char == '[') && $outOfQuotes) {
      $result .= $newLine;
      if ($char == '{' || $char == '[') {
        $pos ++;
      }

      for ($j = 0; $j < $pos; $j++) {
        $result .= $indentStr;
      }
    }

    $prevChar = $char;
  }

  return $result;
}
